universe = vanilla
log = outdir/log_seed12.txt
error = outdir/err_seed12.txt
output = outdir/out_seed12.txt

# Fill in with your own script, arguments and input files
# Note that you don't need to transfer any software
executable = run_seed12.sh
#arguments =
#transfer_input_files =

# Resource requirements
request_cpus = 1
request_memory = 2GB
request_disk = 4GB

#request_gpus = 1
#require_gpus = (GlobalMemoryMb - (MemoryUsage?:0) > 10000 )

# Number of jobs
queue 1
